apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: narkubernetespipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: narkubernetespipelinesjavascriptdocker 
    spec:
      containers:
        - name: narkubernetespipelinesjavascriptdocker 
          image: narcontainerregistry.azurecr.io/narkubernetespipelinesjavascriptdocker
          ports:
          - containerPort: 8080